export const productsData = {
  Seating: [
    {
      id: 1,
      category: "SOFA",
      name: "Oda ottoman",
      price: "$699.00",
      image: "./assets/image/product/1.webp",
    },
    {
      id: 2,
      category: "Dining Chair",
      name: "Ready dining chair",
      price: "$699.00",
      labels: ["Selling fast", "New"],
      image: "./assets/image/product/2.webp",
    },
    {
      id: 3,
      category: "Dining Chair",
      name: "Harbour side dining chair",
      price: "$699.00",
      image: "./assets/image/product/3.webp",
    },
    {
      id: 4,
      category: "SOFA",
      labels: ["-30%"],
      name: "Tearoom club chair",
      priceOld: "$699.00",
      priceNew: "$999.00",
      image: "./assets/image/product/4.webp",
    },

    {
      id: 5,
      category: "Dining Chair",
      name: "OCo dining chair",
      price: "$1,199.00",
      image: "./assets/image/product/4.webp",
    },
    {
      id: 6,
      category: "SOFA",
      name: "Knitting lounge chair",
      price: "$990.00",
      image: "./assets/image/product/6.webp",
    },
  ],
  Table: [
    {
      id: 1,
      category: "Table",
      name: "Blanco Table",
      price: "$999.00",
      image: "./assets/image/product/7.webp",
    },
    {
      id: 2,
      category: "Dining Table",
      name: "Antinomia Dining Table",
      price: "$699.00",
      labels: ["Selling fast"],
      image: "./assets/image/product/8.webp",
    },
    {
      id: 3,
      category: "Table",
      name: "Up Down Coffee & Side Table",
      price: "$699.00",
      image: "./assets/image/product/9.webp",
    },
    {
      id: 4,
      category: "Table",
      labels: ["-40%"],
      name: "Adri Coffee & Side Tables",
      priceOld: "$599.00",
      priceNew: "$999.00",
      image: "./assets/image/product/10.webp",
    },

    {
      id: 5,
      category: "Table",
      name: "Antinomia Dining Table",
      price: "$1,199.00",
      image: "./assets/image/product/11.webp",
    },
    {
      id: 6,
      category: "SOFA",
      name: "Knitting Table",
      price: "$990.00",
      image: "./assets/image/product/12.webp",
    },
  ],
  Storage: [
    {
      id: 1,
      category: "BEDS",
      name: "Jill Bed With Storage",
      price: "$1,299.00",
      image: "./assets/image/product/3.webp",
    },
    {
      id: 2,
      category: "Storage",
      name: "Sami Shelving/Storage",
      price: "$699.00",
      image: "./assets/image/product/12.webp",
    },
    {
      id: 3,
      category: "Dining Chair",
      name: "Harbour side dining chair",
      price: "$699.00",
      image: "./assets/image/product/11.webp",
    },
    {
      id: 4,
      category: "SOFA",
      labels: ["-30%"],
      name: "Tearoom club chair",
      priceOld: "$699.00",
      priceNew: "$999.00",
      image: "./assets/image/product/2.webp",
    },

    {
      id: 5,
      category: "Dining Chair",
      name: "OCo dining chair",
      price: "$1,199.00",
      image: "./assets/image/product/7.webp",
    },
    {
      id: 6,
      category: "SOFA",
      name: "Knitting lounge chair",
      price: "$990.00",
      image: "./assets/image/product/9.webp",
    },
  ],
  Lighting: [
    {
      id: 1,
      category: "Lighting",
      name: "Collier Suspension Light",
      price: "$699.00",
      image: "./assets/image/product/8.webp",
    },
    {
      id: 2,
      category: "Dining Chair",
      name: "Ready dining chair",
      price: "$699.00",
      labels: ["Selling fast", "New"],
      image: "./assets/image/product/10.webp",
    },
    {
      id: 3,
      category: "Dining Chair",
      name: "Harbour side dining chair",
      price: "$699.00",
      image: "./assets/image/product/3.webp",
    },
    {
      id: 4,
      category: "SOFA",
      labels: ["-30%"],
      name: "Tearoom club chair",
      priceOld: "$699.00",
      priceNew: "$999.00",
      image: "./assets/image/product/4.webp",
    },

    {
      id: 5,
      category: "Dining Chair",
      name: "OCo dining chair",
      price: "$1,199.00",
      image: "./assets/image/product/6.webp",
    },
    {
      id: 6,
      category: "SOFA",
      name: "Knitting lounge chair",
      price: "$990.00",
      image: "./assets/image/product/4.webp",
    },
  ],
  Decor: [
    {
      id: 1,
      category: "Decor",
      name: "Silex Mirror",
      price: "$699.00",
      image: "./assets/image/product/2.webp",
    },
    {
      id: 2,
      category: "Dining Chair",
      name: "Ready dining chair",
      price: "$699.00",
      labels: ["Selling fast", "New"],
      image: "./assets/image/product/6.webp",
    },
    {
      id: 3,
      category: "Dining Chair",
      name: "Harbour side dining chair",
      price: "$699.00",
      image: "./assets/image/product/2.webp",
    },
    {
      id: 4,
      category: "SOFA",
      labels: ["-30%"],
      name: "Tearoom club chair",
      priceOld: "$699.00",
      priceNew: "$999.00",
      image: "./assets/image/product/1.webp",
    },

    {
      id: 5,
      category: "Dining Chair",
      name: "OCo dining chair",
      price: "$1,199.00",
      image: "./assets/image/product/4.webp",
    },
    {
      id: 6,
      category: "SOFA",
      name: "Knitting lounge chair",
      price: "$990.00",
      image: "./assets/image/product/3.webp",
    },
  ],
};
